<?php

/**
 * Nexcess.net Turpentine Extension for Magento
 * Copyright (C) 2012  Nexcess.net L.L.C.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

$esiDebugEnabled = (bool)Mage::helper( 'turpentine/esi' )->getEsiDebugEnabled();

if( $esiDebugEnabled ) {
    echo sprintf( '<!-- AJAX START [%s] -->', $this->getNameInLayout() ) . PHP_EOL;
}
echo sprintf( '<div id="turpentine-ajax-block-%s">
<script type="text/javascript">
new Ajax.Request("%s", {
    method: "get",
    on200: function(response) {
        Element.replace($("turpentine-ajax-block-%s"), response.responseText);
    }
});
</script>
</div>',
    $this->getNameInLayout(),
    $this->getAjaxUrl(),
    $this->getNameInLayout() ) . PHP_EOL;
if( $esiDebugEnabled ) {
    echo sprintf( '<!-- AJAX END [%s] -->', $this->getNameInLayout() ) . PHP_EOL;
}
