<?php

/**
 * Nexcess.net Turpentine Extension for Magento
 * Copyright (C) 2012  Nexcess.net L.L.C.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

$ajaxDebugEnabled = (bool)Mage::helper( 'turpentine/ajax' )->getAjaxDebugEnabled();
$blockTag = sprintf( 'turpentine-ajax-block-%s',
    sha1( $this->getNameInLayout() ) );

if( $ajaxDebugEnabled ) {
    echo sprintf( '<!-- AJAX START [%s] -->', $this->getNameInLayout() ) . PHP_EOL;
}
/**
 * Note that the <div/> element is completely replaced with the AJAX response
 * so that it doesn't alter how the block looks.
 *
 * @link http://prototypejs.org/doc/latest/ajax/index.html
 * @link http://prototypejs.org/doc/latest/ajax/Ajax/Request/index.html
 * @link http://prototypejs.org/doc/latest/dom/Element/replace/index.html
 */
echo sprintf( '<div id="%s" style="display: none">
<script type="text/javascript">
new Ajax.Request("%s", {
    method: "get",
    onCreate: function(request) {
        request.transport.setRequestHeader = Prototype.emptyFunction;
    },
    on200: function(response) {
        Element.replace($("%s"), response.responseText);
    }
});
</script>
</div>',
    $blockTag,
    $this->getAjaxUrl(),
    $blockTag ) . PHP_EOL;
if( $ajaxDebugEnabled ) {
    echo sprintf( '<!-- AJAX END [%s] -->', $this->getNameInLayout() ) . PHP_EOL;
}
