<?php

/**
 * Nexcess.net Turpentine Extension for Magento
 * Copyright (C) 2012  Nexcess.net L.L.C.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

$debugEnabled = (bool)Mage::helper( 'turpentine/esi' )->getEsiDebugEnabled();

if( $debugEnabled ) {
    echo sprintf( '<!-- ESI START [%s] -->', $this->getNameInLayout() ) . PHP_EOL;
    echo sprintf( '<!-- ESI URL: %s -->', $this->getEsiUrl() ) . PHP_EOL;
} else {
    echo '<!-- ESI START DUMMY COMMENT [] -->' . PHP_EOL;
    echo '<!-- ESI URL DUMMY COMMENT -->' . PHP_EOL;
}
echo sprintf( '<esi:remove>ESI processing not enabled</esi:remove>
<!--esi <esi:include src="%s" /> -->',
    $this->getEsiUrl() ) . PHP_EOL;
if( $debugEnabled ) {
    echo sprintf( '<!-- ESI END [%s] -->', $this->getNameInLayout() ) . PHP_EOL;
} else {
    echo '<!-- ESI END DUMMY COMMENT [] -->' . PHP_EOL;
}
