<?php

/**
 * Nexcess.net Turpentine Extension for Magento
 * Copyright (C) 2012  Nexcess.net L.L.C.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

$esiData = array(
    'link'      => sprintf( '<esi:remove>ESI processing not enabled</esi:remove>
            <!--esi <esi:include src="%s" /> -->',
        $this->getEsiData()->getUrl() ),
    'debugId'   => $this->getEsiData()->getDebugId(),
    'debugEnabled'  => Mage::helper( 'turpentine/esi' )->getEsiDebugEnabled(),
);

if( $esiData['debugEnabled'] ) {
    echo sprintf( '<!-- ESI START [%s:%s] -->', $this->getNameInLayout(),
        $esiData['debugId'] ) . PHP_EOL;
}
echo $esiData['link'] . PHP_EOL;
if( $esiData['debugEnabled'] ) {
    echo sprintf( '<!-- ESI END [%s:%s] -->', $this->getNameInLayout(),
        $esiData['debugId'] ) . PHP_EOL;
}
